export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const MARK_COMPLETE = 'MARK_COMPLETE';
export const MARK_INCOMPLETE = 'MARK_INCOMPLETE'
export const FILTER_TODO = 'FILTER_TODO';
export const MARKALL_COMPLETED = 'MARKALL_COMPLETED';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';